LOGIN_USERINVALIDO = '!Usuario inexistente!'
LOGIN_PASSINVALIDA = '!Password incorrecta!'
LOGOUT = '!Sesión cerrada exitosamente!'
LOGGED_IN = 'Sesión iniciada'
MENSAJE_USER = '! Bienvenid@!'
MENSAJE = '!OK!'
NOTSERVICES = '!DAToS INCORRECTOS!'
MENSAJE_BIENVENIDA = '¡ Bienvenido(a) al sistema de simulador de inversiones" !'
